In [23]:
import numpy as np
import pandas as pd
from IPython.display import display, Math

A = np.array([[6, -2, -2], [10, -3, 1], [-10, 5, 1]])
B = np.array([[9, 4, -4], [4, 7, 0], [-4, 0, 11]])
C = np.array([[3, 1], [0, -2], [4, 0]])
a = np.array([[5], [1], [2]])
b = np.array([[3, 0, 8]])

def display_matrix(matrix, name):
    matrix_str = "\\begin{bmatrix}"
    if matrix.ndim == 1:
        matrix_str += " & ".join(map(str, matrix)) + " \\\\ "
    else:
        for row in matrix:
            matrix_str += " & ".join(map(str, row)) + " \\\\ "
    matrix_str += "\\end{bmatrix}"
    display(Math(r'\mathbf{' + name + '} = ' + matrix_str))

display_matrix(A @ a, 'Aa')
display_matrix(A @ b.transpose(), 'Ab^T')
display_matrix(A @ B, 'AB')
display_matrix(B @ A, 'BA')
display_matrix(A @ A.transpose(), 'AA^T')
display_matrix(A.transpose() @ A, 'A^TA')
display_matrix(a @ b, 'ab')
display_matrix(b @ a, 'ba')

aminus = a - b.transpose()
display_matrix(aminus, 'a - b^T')
print(np.linalg.norm(aminus)**2)

inner_product = np.inner(a, b.transpose())
print(inner_product)

U1= np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
U2 = np.array([[2, 2, 2], [0, 2, 2], [0, 0, 2]])
L1 = np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]])
L2 = np.array([[2, 0, 0], [2, 2, 0], [2, 2, 2]])
display_matrix(U1 + U2, 'U_1 + U_2')
display_matrix(U1 @ U2, 'U_1 U_2')
display_matrix(U1 + L1, 'U_1 + L_1')
display_matrix(L2 @ L2, 'L_2^2')
display_matrix(L1 @ L2, 'L_1 L_2')

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

41.0
[[15  0 40]
 [ 3  0  8]
 [ 6  0 16]]


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [28]:
a = np.array([[1, 1, 1]])
b = np.array([[2, 3, 1]])
c = np.array([[-1, 1, 0]])

sum_ab = a + b
print(np.dot(sum_ab, c.T))
print(np.sqrt(29))
print(np.linalg.norm(sum_ab))
print(np.sqrt(2))
print( np.linalg.norm(c))
cosine_angle = np.dot(sum_ab, c.T) / (np.linalg.norm(sum_ab) * np.linalg.norm(c))
print(cosine_angle)

[[1]]
5.385164807134504
5.385164807134504
1.4142135623730951
1.4142135623730951
[[0.13130643]]


In [29]:
a = np.array([[1, 1, 3]])
b = np.array([[0, 0, 5]])

projection = (np.dot(a, b.T) / np.dot(b, b.T)) * b
print(projection)

[[0. 0. 3.]]


In [38]:
a = np.array([[0, 4, -3]])
b = np.array([[0, 4, 3]])

projection = ((np.dot(a, b.T) / np.dot(b, b.T))) * b
print(np.dot(a, b.T))
print(np.dot(b, b.T))
print(np.dot(a, b.T) / np.dot(b, b.T))
print(projection)

[[7]]
[[25]]
[[0.28]]
[[0.   1.12 0.84]]
